### PR TITLE
Don't try to use too long filenames.

### PR DESCRIPTION
**Pull request by wastholm**
I'm sure there's some clever way to ask the operating system how long filenames are allowed to be, but simply truncating slugs to 24 characters seems to work.

### CODE REVIEW

**Comment by bdoms** [comment]
Which operating system are you using? This seems like an awfully low limit.

On top of that, this kind of change needs to take into account that two blog posts might have identical names for the first 24 characters. I know I've written posts titled something like "The grand adventures of me on my trip: part 1". If there are 6 parts to that series they're all going to come out the same with this method.

**Comment by wastholm** [comment]
I'm on Linux, and yes, 24 is a completely arbitrary number, and yes, there should be a collision check. My solution is certainly flawed but it was preferable to bombing on "filename too long". I have lots of slugs made up entirely of multi-byte characters (Japanese); this may have contributed to my problems.

**Comment by bdoms** [comment]
I created a new pull request that uses the byte length instead of character length: https://github.com/bdoms/tumblr_backup/pull/17

@wastholm can you please try that and see if it solves your problem?

**Comment by wastholm** [comment]
Thanks @bdoms , it does work. Funny thing, though: I re-ran the master-branch version and that worked too. Not sure how to reproduce the problem but I'll give it another shot.

**Comment by bdoms** [comment]
Merged the other PR that addresses this issue.

**Pull request closed without merging**
